#Prints the date and time in Eastern Standard Time(EST)
#Prints the weather in Stamford, CT


import datetime
import config
from pyowm.owm import OWM
from pyowm.utils import timestamps

whatday = input('1 for today, 2 for tomorrow: ') #Prompt user for whether or not they want today's or tomorrow's report
owm = OWM(config.apikey) #Use the OWM api key generated by website 'https://home.openweathermap.org/api_keys'
mgr = owm.weather_manager()
city_id = 4843564 #ID taken from owmcityidentification.py
observation = mgr.weather_at_id(city_id)
weather = observation.weather
one_call = mgr.one_call(lat=41.053429, lon=-73.538727)
tomorrow = timestamps.tomorrow()
temptmrwmorn = one_call.forecast_daily[0].temperature('fahrenheit').get('feels_like_morn', None)

now = datetime.datetime.now() #Defines variable now as module datetime's class datetime's now()
nextday = now + datetime.timedelta(days=1) #Uses timedelta to define variable nextday as now ahead of one day

#Returns current date, time, and weather
if whatday == '1':
    print ('Current date and time: ')
    print (now.strftime('%Y-%m-%d, %H:%M:%S')) #strftime returns a string defined by an explicit format string
    print ('Current weather: ')
    print (weather.detailed_status)

#Returns data for tommorow morning
if whatday == '2':
    print ('Tomorrow\'s date: ')
    print (nextday.strftime('%Y-%m-%d'))
    print (temptmrwmorn)



