#Uses OWM's city ID registry to find city IDs

from pyowm.owm import OWM
import config

owm = OWM(config.apikey) #Use the OWM api key generated by website 'https://home.openweathermap.org/api_keys'
reg = owm.city_id_registry()
location = 'stamford' #Specify city here
list_of_tuples = reg.ids_for(location) #Makes tuples of ID, city, and country/state
list_of_coordinates = reg.locations_for('Stamford', country='CT')
stamford = list_of_coordinates[0]
lat = stamford.lat
lon = stamford.lon
print (list_of_tuples)
print (lat)
print (lon)

